services:
  linking:
    #image: registry.ethz.ch/library/adl/nla/linking:v1.1
    image: linking:v0.1
    container_name: linking
    user: "${UID}:${GID}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Or specify a number like 1
              capabilities: [gpu]
    environment:
      - USER=${USER}
      - PATH_TO_OUTFILE_FOLDER=/app/nla/data/output
      - PATH_TO_CA_CERT=/certs/ca.crt
      - TZ=Europe/Zurich
    env_file:
      - .env
    volumes:
      - ./private/input:/app/nla/data/input
      - ./private/output:/app/nla/data/output
      - ./private/logs:/app/nla/logs
      - ${PATH_TO_CA_CERT}:/certs/ca.crt:ro
#    command: sh scripts/link_example.sh
