services:
  linking:
    image: linking:v0.1
    container_name: chnobli-linking
    hostname: nla
    user: "${UID}:${GID}"
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all # Or specify a number like 1
    #          capabilities: [gpu]
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - USER=${USER}
      - PATH_TO_OUTFILE_FOLDER=/app/chnobli/nla/data/output
      - PATH_TO_CA_CERT=/certs/ca.crt
      - TZ=Europe/Zurich
      - USE_RICH_LOGGING=false
    volumes:
      - ./private/input:/app/chnobli/nla/data/input
      - ./private/output:/app/chnobli/nla/data/output
      - ./private/logs:/app/chnobli/nla/logs
      - ${PATH_TO_CA_CERT}:/certs/ca.crt:ro
  streamlit_ui:
    build:
      context: services/streamlit_ui
    container_name: streamlit-ui
    hostname: streamlit-ui
    ports:
      - "8501:8501"
    environment:
      - LINKING_CONTAINER=chnobli-linking
      - ELASTIC_BASE_URL=${ELASTIC_BASE_URL}
      - MILVUS_HOST=${MILVUS_HOST}
      - MILVUS_PORT=${MILVUS_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./private/output:/app/output:ro
      - ./configs:/app/configs
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - linking
